### ISSUE TITLE
Unclickable link on GoG in 0.1b8

### ISSUE THREAD

**Issue by ihithim** [ssokolow/itad_importer#13]
in version 0.1b8, the text "EXPORT TO ITAD (THIS PAGE)" appears on the gog account page in both chrome/firefox - tampermonkey/greasemonkey, but the text is not click-able and cannot be interacted with.

**Comment by ssokolow** [comment]
Ugh. I encountered that once before but I thought I fixed it. I guess it's one of those "sometimes it works, sometimes it doesn't" things that are such a pain to debug.

If I can't reproduce the problem, I'll release an update with debug logging and ask you to tell me what it says.

**Comment by ihithim** [comment]
Sounds good. I've not gone into too much detail myself to be honest - I've
not tried disabling other extensions etc but Ill give it a go when i get a
chance and update here with anything I find.

**Comment by ihithim** [comment]
for reference, disabled  all extensions and problem still existed for me

**Comment by ssokolow** [comment]
And I've been unable to replicate the problem. I'll try to get a version with debug logging uploaded later today.

**Comment by ssokolow** [comment]
Sorry for the wait. I've pushed the version with enhanced debug logging. 

Let me know what your Web Console (Ctrl+Shift+K) says when you load your GOG collection page.

**Comment by ihithim** [comment]
firefox has
```
[09:24:34.903] Found invalid value for media feature. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Expected media feature name but found 'min-device-pixel-ratio'. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Unknown property 'transform'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Unknown property 'user-select'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Error in parsing value for 'background'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Unknown property 'box-sizing'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.903] Unknown property 'transition-duration'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.904] Unknown property 'transition'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.904] Error in parsing value for 'display'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.904] Error in parsing value for 'text-overflow'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.904] Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.904] Expected pseudo-element but found '-moz-placeholder'.  Ruleset ignored due to bad selector. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.904] Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.905] Unknown property 'appearance'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.905] Error in parsing value for 'background-image'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.905] Found trailing token after pseudo-element, which must be the last part of a selector:  '.'.  Ruleset ignored due to bad selector. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.905] Unknown property 'text-justify'.  Declaration dropped. @ https://www4-static4.gog.com/css/8f695fb-d2f5897.css:1
[09:24:34.928] Error in parsing value for 'background-image'.  Declaration dropped. @ https://www.gog.com/account:480
[09:24:35.101] Unknown property 'speak'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.101] Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.101] Unrecognized at-rule or error parsing at-rule '@keyframes'. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.101] Unknown property 'box-sizing'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.101] Unknown property 'transform'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.101] Error in parsing value for 'display'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.101] Error in parsing value for 'text-overflow'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Unknown property 'transition'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Unknown property 'appearance'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Expected media feature name but found 'min-device-pixel-ratio'. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Found invalid value for media feature. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Error in parsing value for 'background'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Unknown property 'transition-property'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Error in parsing value for 'background-image'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Unknown property 'animation'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.102] Error in parsing value for 'height'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.103] Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.103] Expected pseudo-element but found '-moz-placeholder'.  Ruleset ignored due to bad selector. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.103] Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.103] Unknown property 'transition-delay'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.103] Error in parsing value for 'word-wrap'.  Declaration dropped. @ https://www4-static1.gog.com/css/6d22ca1-7c82b66.css:1
[09:24:35.140] Error in parsing value for 'position'.  Declaration dropped. @ https://www.gog.com/account
[09:24:35.145] Unknown property 'animation'.  Declaration dropped. @ https://www.gog.com/account:1
[09:24:35.145] Unknown property 'transition'.  Declaration dropped. @ https://www.gog.com/account:1
[09:24:35.206] Unknown property 'transform'.  Declaration dropped. @ https://www.gog.com/account:1
[09:24:35.206] Unrecognized at-rule or error parsing at-rule '@keyframes'. @ https://www.gog.com/account:1
[09:24:35.206] Unknown property '-moz-box-shadow'.  Declaration dropped. @ https://www.gog.com/account:1
[09:24:35.206] Unknown property '-moz-border-radius'.  Declaration dropped. @ https://www.gog.com/account:1
[09:24:35.206] Error in parsing value for '-moz-transition'.  Declaration dropped. @ https://www.gog.com/account:1
[09:24:35.206] Unknown property 'box-sizing'.  Declaration dropped. @ https://www.gog.com/account:1
```
and from chrome
```
Loading ITAD importer...
VM146:485 Matched domain: www.gog.com
VM146:497 Matched profile: ^https?://www\.gog\.com/account(/games(/(shelf|list))?)?/?(\?|$)
VM146:503 Inserting ITAD button for source ID: gog
VM146:253 insert_button called for GOG collection page
```

**Comment by ssokolow** [comment]
Ugh. I forgot that not everyone leaves their browser set to hide the CSS-related log messages by default. None of the Firefox entries are relevant to the issue.

The Firefox output should look pretty much the same as the Chrome output when you're in the Web Console via Ctrl+Shift+K (not the Browser Console via Ctrl+Shift+J) and have CSS deselected in the filter toolbar but I don't see ANY itad_importer-related log lines.

As for Chrome's output, was that with or without trying to click the button? (Because, if you *did* try clicking the button, that means that it's some kind of race condition where GOG is consuming the click event before I get it and then not allowing it to continue propagating.)

**Comment by lkraider** [comment]
Testing on Firefox 40 here, happens only in Grid View for me. See attached screenshots.
![itad-importer-gog-1](https://cloud.githubusercontent.com/assets/52256/8891344/ca42547a-32fb-11e5-9aaa-60ac2dcba756.png)
![itad-importer-gog-2](https://cloud.githubusercontent.com/assets/52256/8891345/d3bfab60-32fb-11e5-9a8d-576532709be1.png)

**Comment by ssokolow** [comment]
Oh! I think I know what's going on! I bet it's binding the click handler properly but the action region is getting covered up by another element. As soon as I've cleared out more urgent stuff for today, I'll push a version with an explicit `z-index`

**Comment by ssokolow** [comment]
Things are taking far longer than expected and I'll have to push the update tomorrow. Sorry.

**Comment by ihithim** [comment]
hah, i didnt even realise there was an alternative to grid layout! well I'm content at least as it seems to work perfectly with the list layout

**Comment by ssokolow** [comment]
Too bad for you. I fixed grid layout anyway. :stuck_out_tongue: 

(Seriously though, my bad. Somewhere along the way, I forgot that grid view existed... which is kind of funny because it's what I used to use exclusively under the old site design.)
